[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
lazy_static = "1.4.0"
obfstr = "0.3.0"
rand = "0.8.5"
rustflags = "0.1.0"
